name: CD Pipeline

on:
  workflow_run:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull rahulrajak/cicd-pipeline:latest

      - name: Delete Old Docker container
        run: sudo docker rm -f cicd-pipeline-container || true

      - name: Run Docker container
        run: sudo docker run -d -p 3000:3000 --name cicd-pipeline-container rahulrajak/cicd-pipeline:latest
